### ISSUE TITLE
no GurobiJni75 in java.library.path

### ISSUE THREAD

**Issue by joleek** [twak/chordatlas#14]
Not sure if this is related to #1 , but I'm trying to run `optimize` on a profile in chordatlas and I get the following error:

```
java.lang.UnsatisfiedLinkError: no GurobiJni75 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at gurobi.GurobiJni.<clinit>(GurobiJni.java:243)
	at gurobi.GRBEnv.<init>(GRBEnv.java:41)
	at org.twak.tweed.gen.GurobiSkelSolver.buildProblem(GurobiSkelSolver.java:262)
	at org.twak.tweed.gen.GurobiSkelSolver.solve(GurobiSkelSolver.java:118)
	at org.twak.tweed.gen.SkelFootprint.solve(SkelFootprint.java:288)
	at org.twak.tweed.gen.SkelFootprint.buildAndSolve(SkelFootprint.java:154)
	at org.twak.tweed.gen.skel.SkelGen.optimize(SkelGen.java:150)
	at org.twak.tweed.gen.skel.SkelGen.lambda$new$1(SkelGen.java:135)
	at java.lang.Thread.run(Thread.java:745)
```

I'm currently running on MacOS 10.13.6. Also, this problem doesn't happen when I run on Ubuntu LTS 14.04. I have to temporarily move off of my Ubuntu machine so I'm trying to run this on my personal MacOS, but this is causing the optimized profile to not be able to be generated. Any clue how to fix this?

**Comment by twak** [comment]
#1 is something different - I want to get rid of gurobi entirely and write my own replacement (since it's only a search through binary choices).

Are you running the latest jar (of from src)? Have you installed and licensed Gurobi? Which version? If you have run the optimiser on ubuntu, it should be the same procedure (if I remember OS X correctly...?) - you have to set the library environment variable when running:

```
LD_LIBRARY_PATH=/wherever/you/installed/gurobi/lib java -jar chordatlas.jar
```

**Comment by joleek** [comment]
Yep - setting the library path solved the problem exactly! I didn't have Gurobi installed on my local MacOS machine, and I guess it must have been installed on my Ubuntu machine by someone else. It would be helpful to list Gurobi as a prerequisite for installation (assuming that #1 is still there, haha).

**Comment by twak** [comment]
great!

the details are there (but hidden) on the ["bigSUR" page](https://github.com/twak/chordatlas/wiki/bigSUR-details). I clarified a little.
