### ISSUE TITLE
Error running super resolution FrankenGAN with ObjSkelGen

### ISSUE THREAD

**Issue by joleek** [twak/chordatlas#18]
I'm testing FrankenGAN on skeletons generated from obj files (ObjSkelGen), and running the net with `super` (the super resolution networks) seems to throw an error. Running FrankenGAN on default (medium) seems to be working without problems.

When I run the net on `super`, it will generate all normal textures, and crash only at the part where the super resolution networks starts to work. Prior to crashing, it would have generated all textures on chordatlas (in other words, if I save the output obj file, I can still see the normal-level textures).

I have a [dropbox link to the obj file](https://www.dropbox.com/s/bbeel5u93y7sqxj/east_cambridge_3.obj?dl=0). It should just be 3 prism-shaped buildings. One interesting thing I noticed is that when I imported the obj, the roofs (which are just flat surfaces) are blue. However, in the video for importing objs ([https://youtu.be/aJek-uGjyc0](https://youtu.be/aJek-uGjyc0)), when you imported the cube, the top of the cube seems to be yellow. Does that make a difference?

The error is as follows:
 ```
finished 24 DoorTexApps
computing FacadeSuperapp
batch 0/37
super remaining 281
Exception in thread "Thread-2" java.lang.NullPointerException at
org.twak.viewTrace.franken.FacadeSuperApp.renderLabels(FacadeSuperApp.java:121)
	at org.twak.viewTrace.franken.FacadeSuperApp.setTexture(FacadeSuperApp.java:52)
	at org.twak.viewTrace.franken.SuperSuper$2.finished(SuperSuper.java:255)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:177)
	at org.twak.viewTrace.franken.SuperSuper.facadeContinue(SuperSuper.java:160)
	at org.twak.viewTrace.franken.SuperSuper.computeBatch(SuperSuper.java:104)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:204)
	at org.twak.viewTrace.franken.App.computeWithChildren_(App.java:161)
	at org.twak.viewTrace.franken.App.access$000(App.java:27)
	at org.twak.viewTrace.franken.App$1.run(App.java:173)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:187)
	at org.twak.viewTrace.franken.App.lambda$computeBatch$0(App.java:204)
	at org.twak.viewTrace.franken.PanesTexApp$4$1.finished(PanesTexApp.java:293)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:177)
	at org.twak.viewTrace.franken.PanesTexApp$4.finished(PanesTexApp.java:284)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeTextures(PanesTexApp.java:279)
	at org.twak.viewTrace.franken.PanesTexApp$3.finished(PanesTexApp.java:216)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:206)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeBatch(PanesTexApp.java:181)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:204)
	at org.twak.viewTrace.franken.App.lambda$computeBatch$0(App.java:204)
	at org.twak.viewTrace.franken.PanesTexApp$4$1.finished(PanesTexApp.java:293)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:177)
	at org.twak.viewTrace.franken.PanesTexApp$4.finished(PanesTexApp.java:284)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeTextures(PanesTexApp.java:279)
	at org.twak.viewTrace.franken.PanesTexApp$3.finished(PanesTexApp.java:216)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:206)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeBatch(PanesTexApp.java:181)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:204)
	at org.twak.viewTrace.franken.App.computeWithChildren_(App.java:161)
	at org.twak.viewTrace.franken.App.access$000(App.java:27)
	at org.twak.viewTrace.franken.App$1.run(App.java:173)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:187)
	at org.twak.viewTrace.franken.App.lambda$computeBatch$0(App.java:204)
	at org.twak.viewTrace.franken.PanesTexApp$4$1.finished(PanesTexApp.java:293)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp$4.finished(PanesTexApp.java:284)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:177)
	at org.twak.viewTrace.franken.PanesTexApp.computeTextures(PanesTexApp.java:279)
	at org.twak.viewTrace.franken.PanesTexApp$3.finished(PanesTexApp.java:216)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:206)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeBatch(PanesTexApp.java:181)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:204)
	at org.twak.viewTrace.franken.App.lambda$computeBatch$0(App.java:204)
	at org.twak.viewTrace.franken.PanesTexApp$4$1.finished(PanesTexApp.java:293)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp$4.finished(PanesTexApp.java:284)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:177)
	at org.twak.viewTrace.franken.PanesTexApp.computeTextures(PanesTexApp.java:279)
	at org.twak.viewTrace.franken.PanesTexApp$3.finished(PanesTexApp.java:216)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:206)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp.computeBatch(PanesTexApp.java:181)
	at org.twak.viewTrace.franken.App.computeBatch(App.java:204)
	at org.twak.viewTrace.franken.App.lambda$computeBatch$0(App.java:204)
	at org.twak.viewTrace.franken.PanesTexApp$4$1.finished(PanesTexApp.java:293)
	at org.twak.viewTrace.franken.Pix2Pix.finished(Pix2Pix.java:213)
	at org.twak.viewTrace.franken.Pix2Pix.submit(Pix2Pix.java:139)
	at org.twak.viewTrace.franken.PanesTexApp$4.finished(PanesTexApp.java:284)
...
```

**Comment by twak** [comment]
great, thanks for the report. Fixed in https://github.com/twak/chordatlas/commit/aec81aad54e8e69c797010595e1c4e52ec8610cb

**Comment by twak** [comment]
beta binary updated https://drive.google.com/open?id=1YSBK4b-Iz9BrdVt6LLAg1ywa0seYaC_p
