### ISSUE TITLE
Unable to load meshes when trying to port to Gurobi 9.0.2

### ISSUE THREAD

**Issue by rooose** [twak/chordatlas#27]
I built chordatlas on my machine to be able to use it with Gurobi 9.0.2. When I load the provided datasets (for example ny_osm), the GIS footprints appear but I am unable to load the meshes on top.

1. Clone and build the project but I change the gurobi version to 9.0.2 in the pom.xml file
2. File > Open > ny_osm > tweed.xml
3. Select the minimesh layer
4. Click on 'load all'
5. Here is the error log:
loading mesh 0 from /Users/roser.hirigoyen/Downloads/ny_osm/minimesh
loading mesh 1 from /Users/roser.hirigoyen/Downloads/ny_osm/minimesh
2020-07-02T10:43:31.848-0400  WARNING  Cannot locate minimesh/1/000000.png (Flipped) (Mipmapped) for material minimesh/1/model.mtl
2020-07-02T10:43:31.851-0400  SEVERE  Exception
java.lang.ClassCastException: com.jme3.asset.AssetKey cannot be cast to com.jme3.asset.TextureKey
	at com.jme3.texture.Texture.setKey(Texture.java:425)
	at com.jme3.scene.plugins.MTLLoader.loadTexture(MTLLoader.java:186)
	at com.jme3.scene.plugins.MTLLoader.readLine(MTLLoader.java:232)
	at com.jme3.scene.plugins.MTLLoader.load(MTLLoader.java:304)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.scene.plugins.OBJLoader.loadMtlLib(OBJLoader.java:336)
	at com.jme3.scene.plugins.OBJLoader.readLine(OBJLoader.java:389)
	at com.jme3.scene.plugins.OBJLoader.load(OBJLoader.java:578)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at org.twak.tweed.gen.MiniGen.calculate(MiniGen.java:116)
	at org.twak.tweed.gen.MiniGen$4$1.run(MiniGen.java:213)
	at com.jme3.app.LegacyApplication$RunnableWrapper.call(LegacyApplication.java:787)
	at com.jme3.app.AppTask.invoke(AppTask.java:142)
	at com.jme3.app.LegacyApplication.runQueuedTasks(LegacyApplication.java:702)
	at com.jme3.app.LegacyApplication.update(LegacyApplication.java:716)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglCanvas.runLoop(LwjglCanvas.java:229)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:748)

At this point, I think all the meshes should have loaded? Even if I try to right click on a single footprint it doesn't work :(

 - OS: MacOS Catalina
 - Version 10.15.5

Thanks a lot for your work, it's really awesome! :)

**Comment by rooose** [comment]
(Also if I copy the 00000.png file from minimesh #0 it manages to load the minimesh! - but it doesnt appear in the layers)

**Comment by twak** [comment]
Hi rooose, thanks for the bug report!

Do you have a branch with the new Gurobi configuration? Did building the version in the repository work for you?

I can try to get it running on Ubuntu (sorry no OSX here).

**Comment by twak** [comment]
Ah, it seems that I'm using this repo for Gurobi mvn integration: 
https://bio.informatik.uni-jena.de/repository/libs-release-oss/gurobi/gurobi-linux64/

They haven't been updated for Gurobi 9. Perhaps the proper way to resolve this is to chase them?

The Gurobi dep has been a problem for many people using the project. Since it is only used in one place, I'm very tempted to pull in a slower IP solution that's more open-source/java-y.

**Comment by rooose** [comment]
Hi! I can make a branch with my changes, I tried to build from stable and master, but for me both need small modifications to their pom.xml (maybe because I'm on mac). I don't think the problem comes from Gurobi, since I have the same error when I build with Gurobi 7.5.2 or 9.0.2 (I installed the new version from the .jar file on my computer)

Replacing Gurobi is going to be a requirement for me as well. I was thinking of trying to replace it with SCIP on my side, maybe I'll be able to help for this task :)

It would still help me a lot if you managed to try and run it on Ubuntu!

**Comment by twak** [comment]
Think I've got the stable branch and relase profile going now and opening ny_osm. Instructions to build and install gurobi [here](https://github.com/twak/chordatlas/wiki/build-instructions). I can't replicate the AssetKey error, but jMonkey was updated which might have solved it.

Let me know if runs.

**Comment by rooose** [comment]
Thanks a lot! :) The solution that worked for me was to build it in eclipse instead of using only the command line.

**Comment by twak** [comment]
Awesome, let me know how you get on!
